// Mock data for Student role
export const STUDENT_MOCK_DATA = {
    metrics: {
        mentorshipRequestsSent: 6,
        activeMentorships: 2,
        referralsRequested: 3,
        interviewExperiencesViewed: 18,
        profileCompletion: 82,
    },
    opportunities: [
        {
            id: "opp-1",
            title: "Software Engineer Intern",
            company: "Google",
            type: "INTERNSHIP",
            location: "Mountain View, CA",
            remote: false,
            domain: "Backend Development",
            status: "REQUESTED",
            requestedDate: "2024-01-15",
            alumniReferrer: "Alex Johnson (2018)",
            isVerified: true,
            verificationBadge: "Institute Verified"
        },
        {
            id: "opp-2",
            title: "Data Analyst",
            company: "Atlassian",
            type: "INTERNSHIP",
            location: "Sydney, Australia",
            remote: true,
            domain: "Data Science",
            status: "IN_REVIEW",
            requestedDate: "2024-01-12",
            alumniReferrer: "Sarah Chen (2019)",
        },
        {
            id: "opp-3",
            title: "Product Trainee",
            company: "Zoho",
            type: "INTERNSHIP",
            location: "Chennai, India",
            remote: false,
            domain: "Product Management",
            status: "REFERRED",
            requestedDate: "2024-01-10",
            alumniReferrer: "Raj Patel (2017)",
            isVerified: true,
            verificationBadge: "Verified Alumni"
        },
        {
            id: "opp-4",
            title: "Full Stack Developer",
            company: "Infosys",
            type: "INTERNSHIP",
            location: "Bangalore, India",
            remote: true,
            domain: "Web Development",
            status: "DECLINED",
            requestedDate: "2024-01-08",
            alumniReferrer: "Priya Sharma (2016)",
        },
    ],
    mentorships: [
        {
            id: "ment-1",
            mentorName: "Michael Chen",
            graduationYear: 2018,
            currentCompany: "Google",
            currentRole: "Senior Software Engineer",
            status: "ACTIVE",
            nextSession: "2024-01-25",
            topic: "System Design",
            messages: 12,
        },
        {
            id: "ment-2",
            mentorName: "Emma Rodriguez",
            graduationYear: 2019,
            currentCompany: "Meta",
            currentRole: "Product Manager",
            status: "PENDING_APPROVAL",
            nextSession: null,
            topic: "Career Guidance",
            messages: 3,
        },
    ],
    interviewExperiences: [
        {
            id: "int-1",
            company: "Microsoft",
            role: "Software Engineer",
            difficulty: "MEDIUM",
            outcome: "SELECTED",
            tags: ["DSA", "System Design", "HR"],
            insights: "The interview process was challenging but fair. Focus on system design patterns and behavioral questions.",
            readTime: "5 min read",
        },
        {
            id: "int-2",
            company: "Amazon",
            role: "SDE Intern",
            difficulty: "HARD",
            outcome: "REJECTED",
            tags: ["DSA", "OOP"],
            insights: "Focus heavily on data structures and algorithms. The bar raiser round is critical.",
            readTime: "7 min read",
        },
        {
            id: "int-3",
            company: "Apple",
            role: "iOS Developer",
            difficulty: "MEDIUM",
            outcome: "AWAITING",
            tags: ["Swift", "OOP", "HR"],
            insights: "Emphasis on design principles and Swift-specific knowledge. Portfolio projects matter.",
            readTime: "4 min read",
        },
    ],
};

// Mock data for Alumni role
export const ALUMNI_MOCK_DATA = {
    metrics: {
        studentsMentored: 12,
        activeMentorships: 3,
        referralsGiven: 7,
        referralSuccessRate: 42,
        openOpportunitiesPosted: 2,
    },
    mentorshipRequests: [
        {
            id: "req-1",
            studentName: "James Wilson",
            degree: "Computer Science",
            graduationYear: 2025,
            topic: "Resume Review",
            messagePreview: "Hi, I'm looking for advice on my resume for internship applications...",
            status: "PENDING",
            requestedDate: "2024-01-15",
            responseTime: "24h",
        },
        {
            id: "req-2",
            studentName: "Sophia Liu",
            degree: "Data Science",
            graduationYear: 2024,
            topic: "System Design",
            messagePreview: "Could you help me prepare for system design interviews?",
            status: "ACCEPTED",
            requestedDate: "2024-01-12",
            responseTime: "2h",
        },
        {
            id: "req-3",
            studentName: "David Kim",
            degree: "Product Management",
            graduationYear: 2025,
            topic: "Career Guidance",
            messagePreview: "I'm interested in transitioning from engineering to product management.",
            status: "DECLINED",
            requestedDate: "2024-01-10",
            responseTime: "48h",
        },
    ],
    referralPipeline: [
        {
            id: "ref-1",
            studentName: "Olivia Parker",
            company: "Netflix",
            role: "Software Engineer",
            status: "REFERRED",
            lastUpdated: "2024-01-14",
            updatedAtRelative: "2 days ago"
        },
        {
            id: "ref-2",
            studentName: "Benjamin Garcia",
            company: "Salesforce",
            role: "Frontend Developer",
            status: "INTERVIEW_SCHEDULED",
            lastUpdated: "2024-01-13",
            updatedAtRelative: "3 days ago"
        },
        {
            id: "ref-3",
            studentName: "Ava Thompson",
            company: "Adobe",
            role: "UX Designer",
            status: "OFFER_RECEIVED",
            lastUpdated: "2024-01-11",
            updatedAtRelative: "5 days ago"
        },
        {
            id: "ref-4",
            studentName: "Noah Martinez",
            company: "Uber",
            role: "Data Analyst",
            status: "REJECTED",
            lastUpdated: "2024-01-09",
            updatedAtRelative: "7 days ago"
        },
    ],
    opportunitiesPosted: [
        {
            id: "post-1",
            title: "Senior Software Engineer",
            department: "Backend",
            experienceLevel: "Mid-Senior",
            applicationsReceived: 24,
            referralSlotsRemaining: 3,
            status: "OPEN",
            postedDate: "2024-01-10",
        },
        {
            id: "post-2",
            title: "Product Manager",
            department: "Growth",
            experienceLevel: "Senior",
            applicationsReceived: 8,
            referralSlotsRemaining: 2,
            status: "OPEN",
            postedDate: "2024-01-05",
        },
    ],
};

// Mock data for Faculty role
export const FACULTY_MOCK_DATA = {
    metrics: {
        totalAlumniRegistered: 1248,
        activeStudentUsers: 612,
        mentorshipMatchRate: 64,
        referralSuccessRate: 31,
        monthlyEngagementTrend: 12,
    },
    analytics: {
        studentAlumniInteractionTrend: [
            { month: "Jan 2024", interactions: 245 },
            { month: "Feb 2024", interactions: 287 },
            { month: "Mar 2024", interactions: 321 },
            { month: "Apr 2024", interactions: 356 },
            { month: "May 2024", interactions: 402 },
            { month: "Jun 2024", interactions: 445 },
            { month: "Jul 2024", interactions: 487 },
            { month: "Aug 2024", interactions: 523 },
            { month: "Sep 2024", interactions: 567 },
            { month: "Oct 2024", interactions: 612 },
            { month: "Nov 2024", interactions: 654 },
            { month: "Dec 2024", interactions: 698 },
        ],
        referralsVsOffers: [
            { month: "Jan 2024", referrals: 45, offers: 18 },
            { month: "Feb 2024", referrals: 52, offers: 22 },
            { month: "Mar 2024", referrals: 58, offers: 25 },
            { month: "Apr 2024", referrals: 63, offers: 28 },
            { month: "May 2024", referrals: 69, offers: 31 },
            { month: "Jun 2024", referrals: 74, offers: 35 },
            { month: "Jul 2024", referrals: 78, offers: 38 },
            { month: "Aug 2024", referrals: 82, offers: 42 },
            { month: "Sep 2024", referrals: 87, offers: 45 },
            { month: "Oct 2024", referrals: 91, offers: 48 },
            { month: "Nov 2024", referrals: 95, offers: 52 },
            { month: "Dec 2024", referrals: 99, offers: 55 },
        ],
        topHiringCompanies: [
            { company: "Google", hires: 128 },
            { company: "Microsoft", hires: 102 },
            { company: "Amazon", hires: 95 },
            { company: "Meta", hires: 87 },
            { company: "Apple", hires: 76 },
        ],
        activeAlumniContributors: [
            { name: "Michael Chen", company: "Google", contributions: 24 },
            { name: "Sarah Johnson", company: "Microsoft", contributions: 18 },
            { name: "David Kim", company: "Amazon", contributions: 16 },
            { name: "Emma Rodriguez", company: "Meta", contributions: 14 },
            { name: "Alex Thompson", company: "Apple", contributions: 12 },
        ],
    },
    moderation: {
        reportedIssues: 2,
        pendingApprovals: {
            alumniVerification: 5,
            opportunityPostings: 3,
        },
        platformHealth: "GOOD", // GOOD, WARNING, CRITICAL
    },
    insights: [
        "Students engaging in mentorship are 2.3× more likely to receive referrals",
        "Alumni participation drops during mid-year; reminder campaigns recommended",
        "Technical roles have higher referral success rates than business roles",
        "Mentorship programs show 42% improvement in student confidence levels",
        "Profile completion above 80% correlates with 3× higher engagement rates",
        "Students who view 10+ interview experiences apply to 40% more opportunities"
    ]
};